# Generated by Django 5.2.8 on 2026-03-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_customuser_tipo_catalogador'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='debe_cambiar_password',
            field=models.BooleanField(default=False, help_text='Si está marcado, el usuario deberá cambiar su contraseña al iniciar sesión', verbose_name='Debe cambiar contraseña'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='rol',
            field=models.CharField(choices=[('catalogador', 'Catalogador'), ('revisor', 'Revisor'), ('admin', 'Administrador')], default='catalogador', help_text='Define los permisos del usuario en el sistema', max_length=20, verbose_name='Rol'),
        ),
    ]
