# Generated by Django 5.2.8 on 2026-02-12 01:40
# El campo subtitulo ya existe desde 0001_initial; esta migracion es un no-op
# (el workaround original fue para SQLite y no aplica a PostgreSQL)

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0006_alter_subdivisioncronologica650_options_and_more'),
    ]

    operations = []
