# Generated by Django 5.2.8 on 2026-02-12 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0006_alter_subdivisioncronologica650_options_and_more'),
    ]

    operations = [
        # Algunos backends (p.ej. SQLite en versiones antiguas) no soportan RENAME COLUMN
        # Necesitamos recrear la tabla con el nombre correcto
        migrations.RunSQL(
            sql="""
                CREATE TABLE catalogacion_tituloalternativo_new (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    titulo varchar(500) NOT NULL,
                    subtitulo varchar(500),
                    texto_visualizacion varchar(500),
                    fecha_creacion datetime NOT NULL,
                    obra_id bigint NOT NULL REFERENCES catalogacion_obrageneral(id)
                );

                INSERT INTO catalogacion_tituloalternativo_new
                    (id, titulo, subtitulo, texto_visualizacion, fecha_creacion, obra_id)
                SELECT id, titulo, resto_titulo, texto_visualizacion, fecha_creacion, obra_id
                FROM catalogacion_tituloalternativo;

                DROP TABLE catalogacion_tituloalternativo;

                ALTER TABLE catalogacion_tituloalternativo_new
                RENAME TO catalogacion_tituloalternativo;

                CREATE INDEX catalogacion_tituloalternativo_obra_id_idx
                ON catalogacion_tituloalternativo(obra_id);
            """,
            reverse_sql="""
                CREATE TABLE catalogacion_tituloalternativo_new (
                    id INTEGER PRIMARY KEY AUTOINCREMENT,
                    titulo varchar(500) NOT NULL,
                    resto_titulo varchar(500),
                    texto_visualizacion varchar(500),
                    fecha_creacion datetime NOT NULL,
                    obra_id bigint NOT NULL REFERENCES catalogacion_obrageneral(id)
                );

                INSERT INTO catalogacion_tituloalternativo_new
                    (id, titulo, resto_titulo, texto_visualizacion, fecha_creacion, obra_id)
                SELECT id, titulo, subtitulo, texto_visualizacion, fecha_creacion, obra_id
                FROM catalogacion_tituloalternativo;

                DROP TABLE catalogacion_tituloalternativo;

                ALTER TABLE catalogacion_tituloalternativo_new
                RENAME TO catalogacion_tituloalternativo;

                CREATE INDEX catalogacion_tituloalternativo_obra_id_idx
                ON catalogacion_tituloalternativo(obra_id);
            """
        ),
    ]
