# Generated by Django 5.2.8 on 2026-03-19 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogacion', '0013_autoridad_persona_campos_bio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediointerpretacion382',
            name='solista',
            field=models.CharField(blank=True, default='---------', help_text='382 $b — Solista (predeterminado: ---------)', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='obrageneral',
            name='arreglo_240',
            field=models.CharField(blank=True, choices=[('arreglo', 'Arreglo')], default='', help_text='240 $o — Arreglo', max_length=10, null=True),
        ),
    ]
